# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Container(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, ip: str=None, active: bool=None, host: str=None):  # noqa: E501
        """Container - a model defined in Swagger

        :param id: The id of this Container.  # noqa: E501
        :type id: str
        :param name: The name of this Container.  # noqa: E501
        :type name: str
        :param ip: The ip of this Container.  # noqa: E501
        :type ip: str
        :param active: The active of this Container.  # noqa: E501
        :type active: bool
        :param host: The host of this Container.  # noqa: E501
        :type host: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'ip': str,
            'active': bool,
            'host': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'ip': 'ip',
            'active': 'active',
            'host': 'host'
        }

        self._id = id
        self._name = name
        self._ip = ip
        self._active = active
        self._host = host

    @classmethod
    def from_dict(cls, dikt) -> 'Container':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Container of this Container.  # noqa: E501
        :rtype: Container
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Container.


        :return: The id of this Container.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Container.


        :param id: The id of this Container.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Container.


        :return: The name of this Container.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Container.


        :param name: The name of this Container.
        :type name: str
        """

        self._name = name

    @property
    def ip(self) -> str:
        """Gets the ip of this Container.


        :return: The ip of this Container.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip: str):
        """Sets the ip of this Container.


        :param ip: The ip of this Container.
        :type ip: str
        """

        self._ip = ip

    @property
    def active(self) -> bool:
        """Gets the active of this Container.


        :return: The active of this Container.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this Container.


        :param active: The active of this Container.
        :type active: bool
        """

        self._active = active

    @property
    def host(self) -> str:
        """Gets the host of this Container.


        :return: The host of this Container.
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host: str):
        """Sets the host of this Container.


        :param host: The host of this Container.
        :type host: str
        """

        self._host = host
